group_vars/mep/vars.yml, group_vars/mep_qa/vars.yml, mep.yml, mep_qa.yml, mep_staging.yml, ppa.yml, ppa_qa.yml, ppa_staging.yml, roles/build_npm/tasks/main.yml, roles/run_webpack/tasks/main.yml, templates/mep/local_settings.py, templates/ppa/local_settings.py
- adds a role for running webpack
- updates playbooks for mep and ppa, incl. staging and qa
- adds media configuration and role to mep
- removes some django-compressor related things that are no longer used
=> add webpack role

README.md, revert_deploy.yml, roles/close_deployment/tasks/main.yml, roles/create_deployment/tasks/main.yml, vagrant/Vagrantfile, vagrant/ansible.cfg, vagrant/staging_vm.yml
This adds a revert_last playbook that can be used to revert a last deploy.
Major question: should this update the GitHub deployment info with a new deploy? I am not 100% on that question.
=> Add playbook to revert previous deploys

roles/close_deployment/tasks/main.yml, roles/create_deployment/tasks/main.yml
=> use deploy_environment var for staging checks

group_vars/pemm/vars.yml, hosts, pemm_qa.yml, roles/build_dependencies/defaults/main.yml, roles/build_dependencies/tasks/main.yml, roles/build_dependencies/templates/tmux.conf.j2, roles/configure_apache/tasks/main.yml, roles/configure_apache/templates/vhosts24.conf.j2, roles/finalize_deploy/tasks/main.yml, roles/install_app_config/defaults/main.yml, roles/install_app_config/tasks/main.yml
Resolves several issues with the playbook:
- connect as pulsys user instead of deploy
- install build dependencies via apt
- properly configure deploy user home directory & .bashrc
- revised apache config so it doesn't cause any errors
=> Updates to PEMM qa playbook 

roles/deploy_user/.yamllint, roles/deploy_user/README.md, roles/deploy_user/defaults/main.yml, roles/deploy_user/meta/main.yml, roles/deploy_user/molecule/default/converge.yml, roles/deploy_user/molecule/default/molecule.yml, roles/deploy_user/molecule/default/verify.yml, roles/deploy_user/tasks/main.yml
=> Create deploy_user role

group_vars/derrida/vars.yml, group_vars/mep/vars.yml, group_vars/ppa/vars.yml, roles/build_dependencies/tasks/main.yml, roles/build_project_repo/tasks/main.yml, roles/build_virtualenv/meta/main.yml, roles/build_virtualenv/tasks/main.yml, roles/configure_logging/tasks/main.yml, roles/configure_media/tasks/main.yml, roles/finalize_deploy/tasks/main.yml, roles/install_local_settings/tasks/main.yml, roles/install_local_settings/templates/ppa_settings.py
When I tried to deploy ppa to qa I ran into a number of problems related to our recent changes for the new pul/ubuntu deploys.
Here are the fixes I needed to get it working again. I haven't tested a pul deploy with this changes, and probably should before merging.
We probably should add the same changes (in terms of the variables I had to add and change for ppa) to the other projects that we might need to deploy (mep, derrida).
=> Adjust deploys so they work for springdale (ppa qa as test case)

group_vars/mep_prod/vars.yml, roles/build_virtualenv/tasks/main.yml
small fixes that were needed for the mep production deploy today
=> Mep prod tweaks

group_vars/cdhweb/vars.yml, group_vars/cdhweb_prod/vars.yml, roles/passenger/templates/passenger.conf.j2
tweak cdhweb settings based on latest deploy
=> cdhweb tweaks

roles/deploy_user/defaults/test.yml, roles/deploy_user/tasks/main.yml, roles/deploy_user/templates/bash_profile.j2, roles/deploy_user/templates/pulsys_bash_alias.j2
- run activate alias by default when logging in as conan
- add alias for pulsys to sudo to conan
=> Add aliases and adjust login to make it easier to activate environment

roles/solr_collection/README.md, roles/solr_collection/defaults/main.yml, roles/solr_collection/tasks/main.yml
- set default number of shards to 3
- add logic to get collection status and modify/reindex if replication configuration has changed
- document role variables in role readme
=> Improve Solr replication handling

group_vars/geniza/vars.yml
* Should I be using the `permanent` flag?
* After your solr PR https://github.com/Princeton-CDH/geniza/pull/495 is merged, presumably I should add a line that handles tags as well?
=> Configure passenger for PGPv3 redirects

group_vars/prosody_prod/vars.yml
For third task of https://github.com/Princeton-CDH/ppa-django/issues/489
=> fixing name for python unit tests in ppa

README.md, group_vars/all/vars.yml, group_vars/prosody_qa/vars.yml, group_vars/qa/vars.yml, hosts, playbooks/replicate.yml
addresses https://github.com/Princeton-CDH/ppa-django/issues/498
=> Setup ppa for replication with replicate playbook

README.md
Part of our PUL/CDH ansiblepalooza.
=> Update README.md with info on skipping deploy tasks

roles/build_dependencies/tasks/main.yml, roles/postgresql/tasks/main.yml, roles/python/tasks/install_dependencies.yml, roles/python/tasks/install_python.yml
These are the fixes I needed to run existing playbooks on bionic machines.
Any reason not to merge these into main so everyone is using them?
=> Adjust steps that are failing on bionic VMs

roles/prosody_setup/tasks/main.yml, roles/setup/tasks/main.yml
nfs4 needs nobody and nogroup
this tests if the conan group and www-data will work with it
=> test the nobody nogroup

inventory/all_hosts
we replaced solr-prod4 with solr-prod7
=> swap out the solr inventory

roles/django/templates/escriptorium_settings.py.j2
Mail now can be sent with these configurations without errors, but my test messages have not yet arrived.
=> Configure HTR to use PUL ponyexpress mail relay

docs/README.md, docs/applications/geniza.md
**Associated Issue:** #254 
- Add documentation page for Geniza application with overview and infrastructure diagram
- Link to new documentation from docs readme
- Please refer to this rendered version so you can see the mermaid.js diagram: https://github.com/Princeton-CDH/cdh-ansible/blob/feature/document-pgp-arch/docs/applications/geniza.md
- If more details are needed, please comment with specifics that you think this documentation should include
=> Documentation for geniza deploy architecture

docs/README.md
This PR improves the documentation for accessing PUL VMs by adding a step-by-step guide for adding new team members to PUL VMs, making it a better onboarding doc for new team members.
- Added detailed instructions for each step of the onboarding process
- Improved formatting and organization for better readability
=> Improve CDH Ansible Documentation
