Princeton-CDH/cdh-ansible

- README.md
- group_vars/all/vars.yml
- group_vars/staging/vars.yml
- mep_qa.yml
- ppa_qa.yml
- ppa_staging.yml
- roles/backup_database/tasks/main.yml
- roles/build_npm/tasks/main.yml
- roles/build_project_repo/tasks/main.yml
- roles/build_virtualenv/tasks/main.yml
- roles/close_deployment/tasks/complete_deploy.yml
- roles/configure_logging/tasks/main.yml
- roles/configure_media/tasks/main.yml
- roles/create_deployment/tasks/fail.yml
- roles/create_deployment/tasks/main.yml
- roles/django_collectstatic/tasks/main.yml
- roles/django_compressor/tasks/main.yml
- roles/django_migrate/tasks/main.yml
- roles/finalize_deploy/tasks/main.yml
- roles/finalize_staging/tasks/main.yml
- roles/install_local_settings/tasks/main.yml
- roles/prep_staging/tasks/main.yml
- roles/restart_httpd/tasks/main.yml
This pull request:
Intended functionality:
1. Ansible creates a deployment in the name of the person who owns the GitHub token
2. Notifies that deploy is pending by settings its status using the GitHub API
3. Closes the deployment as a success if successful, and in all other cases, sets it as error.
> Slack notifications and GitHub deployments

- group_vars/pemm/vars.yml
- group_vars/pemm_qa/vars.yml
- hosts
- pemm_qa.yml
- roles/build_project_repo/tasks/main.yml
- roles/configure_apache/defaults/main.yml
- roles/configure_apache/handlers/main.yml
- roles/configure_apache/tasks/main.yml
- roles/configure_apache/templates/vhosts24.conf.j2
- roles/install_app_config/tasks/main.yml
- roles/install_app_config/templates/app_config
First stab at a playbook to deploy PEMM to a QA ubuntu vm.
Uses a subset of existing roles currently in use for other projects; I expect these will need some modifications in terms of path handling and other things that are specific to SELinux (e.g. `restorecon` call in the finalize deploy).
Adds new roles:
-  `install_app_config` to manage configurations via environment variables in deploy user environment, adapted from pulibrary ansible.
- `configure_apache` to manage apache configuration, adapted from pulibrary ansible
> Initial playbook for PEMM QA deploy

- cdh-web.yml
- cdh-web_qa.yml
- cdh-web_staging.yml
- group_vars/cdh-web/vars.yml
- switches cdhweb to use node v10 for QA and production
- enables the `npm install` step (`build_npm` role) for both QA and production deploys
confirmed that node v10 is available in both environments (currently using in QA; installed in prod).
> use node v10 for cdhweb

- README.md
- adr/0001-use-adr.md
- adr/template.md
- Add ADR template
- Propose usage of ADR, via ADR
> Document architectural decisions

- .github/workflows/molecule_tests.yml
- requirements.txt
- roles/python/.ansible-lint
- roles/python/.yamllint
- roles/python/README.md
- roles/python/defaults/main.yml
- roles/python/meta/main.yml
- roles/python/molecule/default/converge.yml
- roles/python/molecule/default/molecule.yml
- roles/python/molecule/default/prepare.yml
- roles/python/molecule/default/verify.yml
- roles/python/tasks/install_dependencies.yml
- roles/python/tasks/install_python.yml
- roles/python/tasks/main.yml
In writing the django role (#63) it turned out that the only real dependency was python itself; I ended up making a simple role to take care of installing the desired version and create a virtual environment. This is equivalent to our `build_virtualenv` role but for PUL environments, and with a little more functionality.
- Adds a simple role that can install desired python version (including newer versions not in ubuntu repository)
<s>- Role updates symlinks so `python` works correctly in terminal</s>
- Role can create a virtual environment and install dependencies
If we specify this role as a dependency of the `django` role with the following defaults:
```yml
python_app_path: "{{ django_app_path }}"
python_requirements_path: "{{ django_app_path }}/requirements.txt"
```
Then playbooks …
> Create python role (#48)

- group_vars/ppa/vars.yml
- group_vars/ppa_prod/vars.yml
- roles/build_npm/tasks/main.yml
Two changes I needed to successfully deploy PPA to QA. We specified node v10 in the README, but weren't actually using it on VMs. I also got an unpredictable version of `node-sass` that was too new to be compatible with node v10 despite a correct `package-lock.json`, which I determined was because we weren't using `npm ci` to install js dependencies during the deploy.
- Use nodejs v10 for PPA
- Ensure build_npm role installs from package-lock.json
> ppa node fixes

- group_vars/ppa_qa/vars.yml
- requirements.txt
- roles/build_project_repo/tasks/main.yml
I replaced just the rsync step with the git shallow clone, because that's the smallest change that addresses the immediate problem. We could probably replace the full repo checkout (which is what I think you were proposing); I'm just not sure what the implications are and hesitant to make a bigger change for our springdale deploys.
I think Ben's idea with the original setup is that we only have to clone the full repo once, and then once we have it we will only need to pull in incremental changes. I don't actually know if that's any faster than just doing a shallow checkout of the particular version we want.
I had to upgrade ansible to get a version that supported the git options I wanted to use.
Have tested this deploy on both cdh-web qa and derrida qa.
> Use git shallow branch clone instead of rsync #86

- group_vars/all/vars.yml
- group_vars/mep/vars.yml
- group_vars/ppa/vars.yml
- group_vars/ppa_prod/vars.yml
Adding the git 2.27 path for springdale deploys
Because of the way our builds & paths are configured, this currently has to be set in multiple places
~I'm not sure it's actually working correctly; tested it with ppa in qa and still got the warning that the git version is too old for the options we're using.~
I had a path wrong for ppa, and I did not know I needed to also include a new LD_LIBRARY_PATH; I added those and the new deploy worked correctly for PPA in QA
> Add path for git 2.27 to springdale deploys

- group_vars/derrida_crawl_qa/vars.yml
- roles/browsertrix/README.md
- roles/browsertrix/files/derrida-driver.js
- roles/browsertrix/templates/crawl.sh.j2
https://github.com/Princeton-CDH/derrida-django/issues/296
Yay, it works! Two changes that are in this PR that is different from my last run of the crawl:
* I've shortened the sleep before and after a hover. I'm guessing that the reason it didn't work before was not because of load time but because of the URL timing out.
* I'm not including the `--behaviorTimeout`. I think it was specific to non-custom driver features? I didn't fully understand the documentation.
In case we need to go back, here is the docker command that was successful:
```sh
sudo docker run -v /home/pulsys/crawl-config.yaml:/app/crawl-config.yaml \
-v /home/pulsys/crawls:/crawls/ \
-v /home/pulsys/custom-driver.js:/app/custom-driver.js \
webrecorder/browsertrix-crawler crawl \
--config /app/crawl-config.yaml …
```
> 296c configure driver timeout

- README.md
- ansible.cfg
- roles/build_dependencies/tasks/main.yml
- roles/build_npm/tasks/main.yml
- roles/build_project_repo/tasks/main.yml
- roles/configure_logging/tasks/main.yml
- roles/configure_media/tasks/main.yml
- roles/deploy_user/tasks/main.yml
- roles/django/tasks/compilemessages.yml
- roles/passenger/tasks/main.yml
- roles/postgresql/tasks/main.yml
- roles/solr_collection/tasks/main.yml
- tagged one-time setup / provisioning tasks with tag `setup`
- configured setup tag to be skipped by default in ansible config
- updated readme to document the behavior and command to run playbook with setup tasks 
molecule tests are failing, but I think it's not related to these changes... (maybe the keyserver issue? or maybe just got out of date...)
> Skip setup tasks by default

- group_vars/prosody/vars.yml
- group_vars/prosody_qa/vars.yml
- playbooks/prosody.yml
- playbooks/prosody_qa.yml
- roles/passenger/handlers/main.yml
- roles/passenger/tasks/main.yml
per https://github.com/Princeton-CDH/ppa-django/issues/501
in this pr:
- cherry-picked the python version change from the other branch
- revise prosody playbooks to remove apache role and add passenger
- add passenger config variables for prosody and prosody qa
- add handler to passenger to ensure that apache2 is not running when we restart nginx
> Switch prosody deploy from apache2 to nginx/passenger

- roles/django/templates/geniza_settings.py
This PR simply uncomments Arabic on the list of public site languages for Geniza.
> Enable Arabic on Geniza public site settings

- README.md
- roles/finalize_deploy/tasks/main.yml
this change adds an optional pause just before the newly deployed version is made live; must be enabled by specifying with tags
I successfully used this code to deploy an update to the geniza project that switches it to the solr 9 instance, and used the pause to index content into the new solr collection so that there was no downtime with an empty search on the production site while we indexed after the deploy went live.
> Add an optional pause before finalizing deploy

- README.md
- ansible.cfg
- roles/build_dependencies/tasks/main.yml
- roles/build_npm/tasks/main.yml
- roles/build_project_repo/tasks/main.yml
- roles/configure_logging/tasks/main.yml
- roles/configure_media/tasks/main.yml
- roles/deploy_user/tasks/main.yml
- roles/django/tasks/compilemessages.yml
- roles/passenger/tasks/main.yml
- roles/postgresql/tasks/create_db.yml
- roles/postgresql/tasks/create_user.yml
- roles/postgresql/tasks/main.yml
- roles/prosody_setup/tasks/main.yml
- roles/setup/tasks/main.yml
- roles/solr_collection/tasks/main.yml
use `never` to skip setup tasks by default, rather than configuring it as a tag to be skipped by default (which is harder to override)
I haven't run the playbooks with this configuration, but I used the `--list-tasks` option to check and it looks like it's configured properly
> Simplify how setup tasks are skipped

- group_vars/sandbox/simrisk.yml
- hosts
- playbooks/simulatingrisk_dev.yml
- roles/sandbox/tasks/main.yml
- add pulcloud simrisk to hosts inventory and to simrisk playbook
- only run sandbox task on sandbox hosts
- configure simulatingrisk to run at app-specific root path on sandbox only
playbook works, and I was able to deploy to both sandbox and simrisk cloud at the same time 🎉 
- hosts config assumes/requires ssh config is setup for cloud with bastion host; should this be documented anywhere in ansible repo or readme?
- ansible complains that simrisk host == simrisk group; suggestions?
> Update simrisk playbook and vars to deploy to pulcloud

- group_vars/geniza/vars.yml
- group_vars/geniza_qa/vars.yml
- group_vars/shxco_prod/vars.yml
- roles/build_project_repo/tasks/main.yml
- roles/close_deployment/tasks/main.yml
- roles/configure_crontab/tasks/main.yml
- roles/create_deployment/tasks/main.yml
- roles/django/tasks/media.yml
- roles/django/tasks/migrate.yml
- roles/postgresql/tasks/backup_db.yml
- roles/postgresql/tasks/create_db.yml
- roles/postgresql/tasks/create_user.yml
- roles/solr_collection/tasks/main.yml
- add `run_once` to steps that should only be run once even if deploying to multiple hosts
- revise cron role so cron jobs will only be configured on a specified server
> Configure steps that should only run once

- group_vars/all/vars.yml
- roles/build_project_repo/tasks/main.yml
- roles/build_project_repo/tasks/python_app_version.yml
- roles/finalize_deploy/tasks/main.yml
- only set /var/www app symlink and notify restart nginx when passenger is included in playbook roles
- move python app version logic into a separate task file + simplify logic slightly
I've run this successfully on the simrisk playbook. We should test a few others before we merge to main to make sure it doesn't break anything.
> geotaste playbook revisions

- playbooks/replicate.yml
update the replicate playbook to account for multiple hosts in host groups (which we have since the upgrade to jammy)
- use run once on all steps
- assume source host is the first host in the group
@quadrismegistus would you try this branch? I got an error on the step when it tried to remove the old database because it's being accessed by other users, would like to know if happens for you also. (I'm wondering if the other user is the second vm...)
> Update replicate playbook for multiple hosts in groups

- group_vars/geniza_staging/vars.yml
- group_vars/prosody_staging/vars.yml
- group_vars/shxco_staging/vars.yml
- group_vars/staging/vars.yml
- hosts
fixes #190 
- consolidates common solr 8 staging settings in one place
- update configuration to use new solr 8 jammy staging server 
successfully deployed shxco and prosody to staging, created new solr collections, and am indexing the content into the new collections
> Update staging variables for new jammy staging solr server

- playbooks/replicate.yml
- roles/solr_collection/defaults/main.yml
- roles/solr_collection/tasks/backup_solr_collection.yml
- roles/solr_collection/tasks/restore_solr_collection.yml
- roles/solr_collection/vars/main.yml
addresses https://github.com/Princeton-CDH/ppa-django/issues/509
- new tasks in solr_collection role to backup and restore collection
- update replicate playbook to use the new tasks
- add prosody-specific replicate step
This playbook has been used successfully to replicate prosody production to staging.
Open to ideas for better ways to handle app-specific replicate steps. We already have a prosody_setup role, so maybe the task should live there and be included here.
> Add tasks and replicate playbook steps for solr collection replication 

- ansible.cfg
- disable lastpass config vault identity list in ansible.cfg (tower chokes when loading because `lpass` is not installed)
> Updates for ansible-tower

- bin/lpass_default.sh
- bin/lpass_geniza.sh
Inventory sync from this repo to Tower fails with an error about vault passwords not being found. We wondered if the two scripts are somehow making this happen.
> Would removing the scripts make Tower happy?

- inventory/group_vars/all/vars.yml
- roles/setup/handlers/main.yml
- roles/setup/tasks/nfs.yml
- Set nfs domain to princeton.edu 
- revise nfs-idmapd restart handler (unmask, enable, and restart both nfs-server and nfs-imdapd)
I think the domain in the idmapd.conf was the key piece we had wrong. I kept poking at this on other serves and would get it working manually (often working quickly because something was broken), but was never sure which step was the key. This time I got it manually working on cdh-web3 and then by trial and error got ansible to do the same thing on cdh-web4.
> Get NFS idmapd working with ansible

- inventory/group_vars/htr_staging/vars.yml
- playbooks/escriptorium.yml
- roles/django/templates/escriptorium_settings.py.j2
- deploy a tagged version of escriptorium
- set environment variable so the tag will be displayed as the version on the homepage
- install new htr2hpc package as an additional python dependency for customizing the install
- use htr2hpc in local settings and configure CAS authentication
> escriptorium refinements: deploy specific tagged version, enable CAS authentication

- requirements.txt
- roles/example/.ansible-lint
- roles/example/.yamllint
- roles/example/meta/main.yml
- roles/example/molecule/default/converge.yml
- roles/example/molecule/default/molecule.yml
- roles/example/molecule/default/verify.yml
we use `molecule-plugin[docker]` to install the docker driver used by
molecule 5.0
and an example directory with the meta and files needed by molecule to
run
related to #45
Co-authored-by: Beck Davis <beck-davis@users.noreply.github.com>
Co-authored-by: Vickie Karasic <vickiekarasic@users.noreply.github.com>
> update molecule docker driver

- inventory/group_vars/geniza_production/vars.yml
- inventory/group_vars/geniza_staging/vars.yml
- inventory/group_vars/prosody_production/vars.yml
- inventory/group_vars/prosody_staging/vars.yml
resolves #226
On solr 9 the command line zk upload command used to create/update a configset requires this change to the zk host string.
> Correct the zookeeper host string for zk upload of configset for Solr 9

- inventory/group_vars/shxco/vars.yml
- inventory/group_vars/shxco_production/vars.yml
- inventory/group_vars/shxco_staging/vars.yml
- playbooks/shxco.yml
Per #258:
- Update the vars and playbook for S&Co. to use the solr 9 variables and host settings
- Modeled after geniza and ppa settings
> Update shxco deploy for solr 9 (#258)

- inventory/group_vars/shxco/vars.yml
- roles/django/templates/shxco_settings.py.j2
**Associated Issue(s):** Princeton-CDH/mep-django#849
- Update path to local settings in `shxco/vars.yml`
- Update settings template to not rely on `os` import
> Update S&Co config for Django split settings

- inventory/group_vars/shxco/vars.yml
**Associated Issue(s):** #265
- Set `python_version` in shxco group_vars
> Update shxco config to use Python 3.12 (#265)

- inventory/group_vars/shxco/vars.yml
- roles/python/tasks/install_python.yml
**Associated Issue(s):** #265
- Ensure distutils package is only installed for python < 3.12, as it was [removed from python](https://docs.python.org/3/library/distutils.html) in that version.
- Prevent error on S&Co:
`fatal: [cdh-test-shxco1.princeton.edu]: FAILED! => {"changed": false, "msg": "No package matching 'python3.12-distutils' is available"}`
- Is there a way I can test this before running it in tower? Should I just do the resync and then run off this branch before merging? I imagine we want to make sure it doesn't break other scripts using this task…
- Hopefully I got the ansible yaml syntax right, it's still new to me (had to look up how to ensure that `python_version` is compared correctly using [this test](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/v …
> Handle distutils/setuptools for python 3.12 (#265)

- inventory/group_vars/prosody_production/vars.yml
- roles/configure_crontab/tasks/main.yml
- configure_crontab role now supports weekday configuration in host vars
- prosody variables updated to specify numeric weekday
- Fixed to correct a bug that was found in production - cron job was running every week day for the first of the month, instead of on Saturdays only as intended.
- Playbook has already been run with the crontab tag to update the cron job with the corrected configuration. I checked the resulting config with [crontab.guru](https://crontab.guru/#0_2_1-7_*_6)
> Update crontab role to support weekday; update prosody vars to specify weekday correctly

- inventory/group_vars/prosody/vars.yml
**Associated Issue(s):** #264
- Change `python_version` to 3.12 for PPA upgrades
> Set python version to 3.12 for PPA (#264)

- inventory/group_vars/geniza/vars.yml
**Associated Issue(s):** https://github.com/Princeton-CDH/geniza/issues/853
- Bump the python version to 3.12 and the node version to 22 for geniza in Ansible vars
- According to this comment, it looks like we may have to manually upgrade node on the server:
https://github.com/Princeton-CDH/cdh-ansible/blob/013fd75dfa9c857d025b97b02c95e2072166264a/roles/build_npm/tasks/main.yml#L22-L25
But we can try running the deploy playbook as usual first and do the manual upgrade if it fails.
> Upgrade python (3.12) and node (22) on geniza

- .github/workflows/molecule_tests.yml
- pyproject.toml
- roles/deploy_user/molecule/default/converge.yml
- roles/deploy_user/molecule/default/molecule.yml
- roles/deploy_user/molecule/default/verify.yml
- uv.lock
**Associated Issue:** ~
- Updated molecule configuration for deploy_user to use current PUL jammy image and configuration
- Updated python dependencies to use newer versions of ansible and molecule
- Correct an assertion error in the deploy_user molecule verify 
- Updated github actions for molecule testing to use better role for uv setup, and revised list of roles to be tested
- I ran into an error where molecule couldn't find the role that it belongs to; I found this issue and adapted a solution I found there: https://github.com/ansible/molecule/issues/4391
- Molecule test succeeds locally and I thought I got a meaningful error on github but now I'm getting a temp directory permission error
- Only testing one scenario but I can see now it would be useful to test one case where user does …
> Update molecule for deploy_user role and restore molecule tests workflow

- .pre-commit-config.yaml
**Associated Issue(s):** ~
- Configures [action-validator](https://github.com/mpalmer/action-validator?tab=readme-ov-file) to run as a pre-commit hook
> Configure a pre-commit hook to validate github action workflow files
